version: '3'
volumes:
  postgres_data: {}
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    depends_on:
      - db
      - redis
      - sidekiq
    environment:
      - RAILS_SERVE_STATIC_FILES=true
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/web/DockerFile
    depends_on:
      - app
    ports:
      - 80:80
  redis:
    image: 'redis'
  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - 'db'
      - 'redis'