template "k8s/README.md.tt"
template "k8s/lets_encrypt_issuer.yaml.tt"
template "k8s/ingress.yaml.tt"
template "k8s/app.yaml.tt"
template "k8s/demo.yaml.tt"
template "k8s/config-maps/nginx-conf.yaml.tt"