copy_file 'lib/tasks/deploy.rake'
copy_file 'lib/tasks/hot.rake'
template 'lib/generators/stimulus/templates/controller.js.erb.tt'
copy_file 'lib/generators/stimulus/stimulus_generator.rb'
copy_file 'lib/generators/stimulus/USAGE'
